// Reads the four Flexciton knowledge-base markdown docs at the project root and
// bakes them into a single committed source file, site/data/kb-context.ts, that
// the Flexi chatbot API route loads at runtime.
//
// Why a generated file: the repo root is `site/`, and the KB docs live one level
// above it and are NOT in the repo — so a runtime `fs.readFile("../../ICP.md")`
// would not exist on Vercel. This script is the bridge. Re-run it (via
// `npm run build:kb`, also part of `npm run match`) whenever a KB doc changes,
// and commit the result.

import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(__dirname, "..", "..");
const OUT_FILE = path.resolve(__dirname, "..", "data", "kb-context.ts");

// The KB is an internal GTM doc; some of it is explicitly not for external eyes
// (its own rules: "never name a competing vendor in external-facing content",
// "do not quote fixed numbers"). Flexi is prospect-facing, so scrub those items
// from the bundle rather than rely on the model to withhold text it can see.
// Review this list whenever the root KB docs change.
const REDACTIONS: Array<[RegExp, string]> = [
  // Competing product / vendor names -> generic.
  [/\bAMAT\s+AutoSched\b/gi, "a commercial simulation tool"],
  [/\bAutoSched\b/gi, "the incumbent simulation tool"],
  // Cost anchors: dollar figures in a per-fab / per-year pricing context, and the
  // internal market-sizing / LTV lines. Customer-outcome and capex-decision
  // figures ($6.8M revenue impact, $40M tool investment, $10M capex) are left intact.
  [/~?\$\s?\d{2,3}\s?[kK](?:\s*(?:to|–|-)\s*\$?\s?\d{2,3}\s?[kK])?\s*(?:\/|per\s)\s*fab(?:\s*(?:\/|per\s)\s*year)?/g, "a price comparable to incumbent tools"],
  [/~?\$\s?\d{2,3}\s?[kK](?:\s*(?:to|–|-)\s*\$?\s?\d{2,3}\s?[kK])?\s*(?:\/|per\s)\s*year/g, "a price comparable to incumbent tools"],
  [/\bPricing around \$\s?\d{2,3}\s?[kK][^.]*\./g, "Entry pricing keeps the hurdle low."],
  [/^-?\s*\*\*(?:SAM|SOM|LTV per fab)\*\*.*$/gim, ""],
];

function sanitize(text: string): string {
  let out = text;
  for (const [pattern, replacement] of REDACTIONS) {
    const before = out;
    out = out.replace(pattern, replacement);
    if (out !== before) {
      const n = (before.match(pattern) ?? []).length;
      console.log(`  redacted ${n}× ${pattern}`);
    }
  }
  return out;
}

// Order matters only for readability; all four are always sent in full.
const DOCS = [
  "value prop.md",
  "ICP.md",
  "Flexciton_Master_Knowledge_Base.md",
  "Capacitor KB.md",
];

function main() {
  const parts: string[] = [];
  for (const name of DOCS) {
    const file = path.join(ROOT, name);
    if (!fs.existsSync(file)) {
      console.error(`Missing KB doc: ${file}`);
      process.exit(1);
    }
    const body = sanitize(fs.readFileSync(file, "utf-8").trim());
    parts.push(`===== DOC: ${name} =====\n\n${body}`);
    console.log(`✔ ${name} (${body.length.toLocaleString()} chars)`);
  }

  const combined = parts.join("\n\n\n");
  // base64 so the content can hold any characters (backticks, ${…}, etc.) without
  // escaping, and is decoded once at module load.
  const encoded = Buffer.from(combined, "utf-8").toString("base64");

  const out = `// GENERATED by scripts/build-kb.ts — do not edit by hand.
// Regenerate with \`npm run build:kb\` whenever the root KB docs change, then commit.
// Source docs: ${DOCS.join(", ")}.

const ENCODED =
  "${encoded}";

/** The full text of all four Flexciton KB docs, concatenated with delimiters. */
export const KB_CONTEXT: string = Buffer.from(ENCODED, "base64").toString("utf-8");
`;

  fs.writeFileSync(OUT_FILE, out);
  console.log(
    `✔ data/kb-context.ts (${combined.length.toLocaleString()} chars of KB, ${encoded.length.toLocaleString()} encoded)`,
  );
}

main();
